### ISSUE TITLE
deploy: build The set-output command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by Mieekaserra** [just-the-docs/just-the-docs-template#11]
I've tried this and am still getting the error (on a different line)
Run ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
Modifying PATH
Downloading Ruby
Extracting  Ruby
Print Ruby version
Installing Bundler
bundle install

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mattxwang** [comment]
Eagle eyes - turns out, the version pinned by the core workflow is outdated. Probably should get around to updating that soon in the main repo, but in the meantime, have resolved by #12 - see [the build output](https://github.com/just-the-docs/just-the-docs-template/actions/runs/3723882227/jobs/6315670418). Thanks for submitting the issue!

**Comment by mattxwang** [comment]
FYI, submitted https://github.com/actions/starter-workflows/pull/1869 upstream!
