### ISSUE TITLE
Missing documentation step (enabling GitHub Pages as deploy source)

### ISSUE THREAD

**Issue by christiansievers** [just-the-docs/just-the-docs-template#17]
I'm new to GitHub Actions, and I'm still wrapping my head around this, so please excuse me if I'm missing something obvious. 

So I've cloned the template repo and followed the instructions in <https://github.com/just-the-docs/just-the-docs-template#publishing-your-site-on-github-pages>. 

No. 3 is where I ran into problems. I suppose GitHub should find the workflows/pages.yml automatically, but it doesn't. Instead it offers me to create a workflows/jekyll.yml action, which is similar but not the same:
<https://imgur.com/a/55jv83E>

This jekyll.yml action gets triggered automatically when I push a commit to the site. My solution was to somehow add the pages.yml action and delete jekyll.yml.

**Comment by mattxwang** [comment]
Thank you for submitting an issue @christiansievers!

To repro, I've created https://github.com/mattxwang/jtd-template-repro-17 (using *just* the "use this template button", with nothing else - including settings changes). I can confirm that I can reproduce *an* issue (which does seem like the one you're facing); namely, that [the GET pages action fails](https://github.com/mattxwang/jtd-template-repro-17/actions/runs/4561151763/jobs/8046789644#step:4:6).

(I'm assuming you ran into this problem here: https://github.com/Digi-Kunst/Handreichung/commit/334e3ac582f1cca9172dc04e1a3c46b8cdd95ba6)

The cause of this problem is that, by default, building GitHub Pages from actions is disabled. See this view in Settings > Pages:

![settings page for github repo's github pages; build source is from branch, and not github actions](https://user-images.githubusercontent.com/14893287/228745391-88ea26eb-86a6-4381-b3e8-c67efcfbc6ea.png)

If I change it to now use GitHub Actions:

![settings page for github repo's github pages; build source is now github actions](https://user-images.githubusercontent.com/14893287/228745543-53f0b19a-e0e3-4212-89a2-52e2457d5525.png)

And then [re-run the action](https://github.com/mattxwang/jtd-template-repro-17/actions/runs/4561151763/jobs/8046867184), it now succeeds! Note here that I haven't made any new commits or changed any files.

I don't think there's a way we can change the default GitHub Pages/Actions option (this is probably there for a reason!). But, we can better document the workflow to instruct users to toggle this option.

@christiansievers is this an accurate description of what happened / what are your thoughts? If you'd like to write up the documentation, a PR is gladly welcome; if not, I can do it soon-ish.

**Comment by christiansievers** [comment]
Hi Matt,

thanks for that. I've tried again and documented what happens at each step:

1. Generate repository from link in Readme
2. I immediately get a first email "Run cancelled: Deploy Jekyll site to Pages"
3. Go to Actions. There are two workflow runs called "Initial commit". The second one is still running, then fails (makes sense, didn't enable Actions in Pages yet)
4. Edit .yml, commit
5. Go to Actions. There's another action running. Ignoring that, it'll fail.
6. 
7. Go to the Settings tab -> Pages -> Build and deployment, then select Source: GitHub Actions.
8. Go to Actions. No action has been started by that change in settings. I open the latest (failed) action and choose "Re-run failed jobs"
9. Now [the action (build and deploy) works fine](https://github.com/christiansievers/just-the-test/actions/runs/4562452251). 
10. (there's no email that says "Success" btw, so I guess you only get emails if something fails)

So it kind of works, but you get a lot of error messages first. I'm sorry but I wouldn't know how to get rid of those. Also, it looks like you need to use the button that asks you to configure Jekyll after enabling Actions, but you don't. So that is misleading/ was not clear to me.

**Comment by mattxwang** [comment]
Thanks for your quick response and patience @christiansievers!

Okay, given what you've said, I've confirmed my inutition -- the problem is that step `7` is necessary but undocumented (steps 2-5 aren't relevant). I'll have to add that to the documentation in our template.

If you'd like, a PR is welcome to do so - if not, I'll knock it out as an item in my backlog.

> So it kind of works, but you get a lot of error messages first. I'm sorry but I wouldn't know how to get rid of those. Also, it looks like you need to use the button that asks you to configure Jekyll after enabling Actions, but you don't. So that is misleading/ was not clear to me.

Ah, yes, these are all product decisions from GitHub's side - we're not able to change that. I can see if there's some way we can change the default build source, but I doubt it. Thanks for looking into this!
