### ISSUE TITLE
Code folding support

### ISSUE THREAD

**Issue by rbutleriii** [just-the-docs/just-the-docs-template#36]
I was trying to implement collapsible code (or ideally folded with the first couple lines visible) in my site, but the general methods for [workarounds for github](https://github.com/dear-github/dear-github/issues/166) don't seem to translate to Jekyll.
```
### R script header

<details>
  <summary>Summary</summary>
  <!-- have to be followed by an empty line! -->

    ```r
    #!/usr/bin/env Rscript
    ## ---------------------------
    ```
</details>
```
![image](https://github.com/just-the-docs/just-the-docs-template/assets/6644896/0855f637-ed5c-447b-9272-3b93cf009f85)

**Comment by pdmosses** [comment]
Unfortunately, Jekyll uses a different [parser for "GitHub Flavored Markdown"](https://jekyllrb.com/docs/configuration/markdown/#kramdown-processor) than GitHub. What works on GitHub doesn't always work with Jekyll 🙄 (and the other way round, which is why the [GitHub preview doesn't render the call-outs in the theme home page](https://github.com/just-the-docs/just-the-docs/blob/main/index.md)).

The following markup works with Jekyll:

````markdown
### R script header

<details markdown=1>
  <summary>Summary</summary>
```r
#!/usr/bin/env Rscript
## ---------------------------
```
</details>
````

![image](https://github.com/just-the-docs/just-the-docs-template/assets/18308236/21e70fb0-588d-4613-97b2-396f2c6ee60e)
