### ISSUE TITLE
The just-the-docs theme could not be found

### ISSUE THREAD

**Issue by glasseszoom0p** [just-the-docs/just-the-docs-template#42]
I am only using the template, and ‘theme: just-the-docs’ is the only line I’m changing.

When I use ‘theme: just-the-docs,’ the site works locally and appears normal on the web, but there are two build errors:
- Logging at level: debug Configuration file: /github/workspace/./_config.yml Theme: just-the-docs github-pages 231 | Error: The just-the-docs theme could not be found. 
- The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/

When I use ‘remote_theme: just-the-docs/just-the-docs,’ the site does not work locally (there is no formatting, just plain text), but the site works normally on the web, and there are no build errors

What do I do? The site is https://glasseszoom0p.github.io/wiki/
I don’t want to use GitHub Actions because they have limitations and are not free after a certain point.

**Comment by mattxwang** [comment]
Thanks for submitting an issue @glasseszoom0p! If you don't want to use GitHub Actions directly to deploy your site, that's okay (though I will point out that the `github-pages` gem uses Actions under the hood anyways).

The simplest way to do that would be to use the remote theme option. To do that, you would:

1. change your `Gemfile` to only use the `github-pages` gem, like so:
```rb
source 'https://rubygems.org'
gem 'github-pages'
```
2. change the `_config.yml` to use `remote_theme`, as you've done:
```yaml
just-the-docs/just-the-docs@v0.7.0 # here, i've pinned it to the latest release so that your site doesn't auto-update when we change versions; you can remove the @0.7.0 if you'd like this behaviour
```
3. to resolve the local build issue, re-run `bundle install` (to install `jekyll-remote-theme`) and then develop using `bundle exec jekyll serve` and/or `bundle exec jekyll build`
4. finally, delete the `.github/workflows` folder, since you don't want to use GitHub Actions directly

This should resolve your problem; let me know if it doesn't!

**Comment by mattxwang** [comment]
(going to close this due to inactivity)
